# Generated by Django 6.0.6 on 2026-06-18 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wpis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('wiadomosc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wpis_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vahicle_name', models.TextField()),
                ('vahicle_model', models.TextField()),
                ('vahicle_rok', models.TextField(max_length=4)),
            ],
        ),
    ]
